### Spring properties
# Service registers under this name
spring:
  application:
    name: messages-microservice
  data:
    mongodb:
      database: messages
      host: localhost
      port: 27017

# Discovery Server Access
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 5555

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false